version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_wipi_fibra_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - "5432:5432"

volumes:
  postgres_wipi_fibra_data:
